export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"项目主页","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-62633a0e","/dl/basic.html",{"y":"a","t":"基础知识"},[":md"]],
  ["v-2d0a830e","/dl/",{"y":"a","t":"深度学习","i":"lightbulb"},["/dl/readme.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-2d035e0f","/dl/neural_de/background.html",{"y":"a","t":"介绍"},[":md"]],
  ["v-3f2786dc","/dl/neural_de/",{"y":"a","t":"神经微分方程"},["/dl/neural_de/readme.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-48487511","/dl/neural_de/node/",{"y":"a","t":"引入","i":"lightbulb"},["/dl/neural_de/node/README.md"]],
  ["v-a8d6da06","/dl/neural_de/node/%E8%A1%A8%E7%A4%BA%E5%92%8C%E9%80%BC%E8%BF%91.html",{"y":"a","t":"表示和逼近能力"},["/dl/neural_de/node/表示和逼近.html","/dl/neural_de/node/表示和逼近.md",":md"]],
  ["v-558b68aa","/dl/neural_de/node/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-56238b0d","/dl/neural_de/node/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/dl/neural_de/node/bar/README.md"]],
  ["v-8ff76cae","/dl/neural_de/node/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-562590ba","/dl/neural_de/node/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/dl/neural_de/node/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
